name: Feature request
description: Suggest an additional feature you'd like to see in suite2p.
title: "FEATURE: <Please write a comprehensive title after the 'FEATURE: ' prefix>"

body:
- type: textarea
  attributes: 
    label: "Feature you'd like to see:"
    description: >
        Provide a clear and concise description of what problem you'd like this feature to address. 
        Then, provide a clear description of the solution you'd like to see.
  validations:
    required: true

- type: textarea
  attributes:
    label: "Attempted alternative approaches:"
    description: >
       Provide a description of alternative approaches you've tried. 
  validations:
    required: true

- type: textarea
  attributes:
    label: "Additional Context"
    description: >
        Add any other context or screenshots about the feature request here.
